import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={'min-h-screen flex flex-col ${inter.className}'}>
          <Header className="sticky top-0 z-10" />
          <main className="flex-grow">
              {children}
          </main>
          <Footer className="sticky bottom-0 z-10" />
      </body>
    </html>
  );
}
